// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Contents: typeof import('./components/docs/Contents.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    CustomerTable: typeof import('./components/CustomerTable.vue')['default']
    Heading: typeof import('./components/docs/Heading.vue')['default']
    LanguageSwitcher: typeof import('./components/LanguageSwitcher.vue')['default']
    NavAside: typeof import('./components/NavAside.vue')['default']
    NavItem: typeof import('./components/NavItem.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouteItem: typeof import('./components/RouteItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./components/SearchBar.vue')['default']
    TicketTable: typeof import('./components/TicketTable.vue')['default']
    Topbar: typeof import('./components/Topbar.vue')['default']
  }
}
